version: '3.8'
services:
  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ${DATA_DIR:-./data}:/app/data:rw
      - ${IMG_DIR:-./img}:/app/img:rw
      - ${STREAMLIT_DIR:-./app/.streamlit}:/app/.streamlit:rw
    env_file:
      - .env
    restart: always
