services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./app/.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    restart: always