services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fondedenaja_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ${DATA_DIR:-./data}:/app/data:rw
      - ${IMG_DIR:-./img}:/app/img:rw
      - ${STREAMLIT_DIR:-./app/.streamlit}:/app/.streamlit:rw
    env_file:
      - .env
    restart: always
