import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))

default_data = "data"
default_img = "img"
default_app = "app"
env_path = os.path.join(BASE_DIR, ".env")
config_file = os.path.join(BASE_DIR, default_data, "settings.yaml")

print("=== FonDeDeNaJa Setup ===")

data_dir = input(f"Enter config directory path [{default_data}]: ").strip() or default_data
img_dir = input(f"Enter image directory path [{default_img}]: ").strip() or default_img
app_dir = input(f"Enter app directory path [{default_app}]: ").strip() or default_app

data_path = os.path.join(BASE_DIR, data_dir)
img_path = os.path.join(BASE_DIR, img_dir)
app_path = os.path.join(BASE_DIR, app_dir)

os.makedirs(data_path, exist_ok=True)
os.makedirs(img_path, exist_ok=True)
os.makedirs(app_path, exist_ok=True)

# Create .env
env_content = f"""# Directory Auto-generated by setup.py
CONFIG_DIR=./{data_dir}
IMG_DIR=./{img_dir}
"""

if os.path.exists(env_path):
    print("[!] .env already exists. Skipping write.")
else:
    with open(env_path, "w") as f:f.write(env_content)
    print("[✓] .env created.")

# Create default config file if it doesn't exist
config_path = os.path.join(data_path, "settings.yaml")
if not os.path.exists(config_path):
    with open(config_path, "w") as f:
        f.write("""# Default application config
[app]
debug = false
title = "FonDeDeNaJa"
""")
    print(f"[✓] Default config written to {config_path}")
else:
    print(f"[!] Config file already exists: {config_path}")

print("[✓] Setup complete.")
print(f"  - Config directory: {data_path}")
print(f"  - Image temp dir : {img_path}")
print(f"  - App directory  : {app_path}")
