[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "X8Ot3hzwwoCV4G6fg5siA2J5sLUpBiqL"
client_id = "698506390216-5av8oacn1158giq45ujfsoosv99kdltc.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"